import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GuestLayout({ children }) {
  return (
    <main>
      <header></header>
      <div class='main-container'>
        <aside></aside>
        <section>
          {/* only edit this section */}
          {children}
        </section>
      </div>
      <footer></footer>
    </main>
  );
}
