import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import SideNav from "./components/Sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GuestLayout({ children }) {
  return (
    <main>
      <header>
        <Navbar />
      </header>
      <div class='main-container'>
        <aside>
          <SideNav />
        </aside>
        <section>
          {/* only edit this section */}
          {children}
        </section>
      </div>
    </main>
  );
}
